export const LAY_DANH_SACH_NGUOI_DUNG_SUCCESS =
	'LAY_DANH_SACH_NGUOI_DUNG_SUCCESS';
export const LAY_DANH_SACH_NGUOI_DUNG_REQUEST =
	'LAY_DANH_SACH_NGUOI_DUNG_REQUES';
export const THEM_NGUOI_DUNG = 'THEM_NGUOI_DUNG';
export const TIM_KIEM_NGUOI_DUNG = 'TIM_KIEM_NGUOI_DUNG';
